# Generated by Django 2.0.2 on 2018-09-07 08:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauthor', models.CharField(max_length=20)),
                ('bpress', models.CharField(max_length=20)),
                ('btitle', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=20)),
                ('original_title', models.CharField(max_length=50)),
                ('translator', models.CharField(max_length=20)),
                ('publication_date', models.DateField()),
                ('number_of_pages', models.IntegerField()),
                ('bprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bscore', models.DecimalField(decimal_places=1, max_digits=3)),
                ('popularity', models.DecimalField(decimal_places=0, max_digits=7)),
                ('content_validity', tinymce.models.HTMLField()),
                ('introduction_to_author', tinymce.models.HTMLField()),
                ('tags', models.CharField(max_length=50)),
                ('bpic', models.ImageField(upload_to='static/books')),
                ('bfile_mobi', models.FileField(upload_to='file_mobi')),
                ('bfile_azw3', models.FileField(upload_to='file_azw3')),
                ('bfile_epub', models.FileField(upload_to='file_epub')),
                ('bfile_pdf', models.FileField(upload_to='file_pdf')),
                ('bfile_txt', models.FileField(upload_to='file_txt')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gclick', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_books.TypeInfo'),
        ),
    ]
