# Generated by Django 2.0.2 on 2018-09-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsInfo',
            new_name='booksinfo',
        ),
    ]
