# Generated by Django 2.0.2 on 2018-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_books', '0002_auto_20180907_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinfo',
            name='bauthor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booksinfo',
            name='bpress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booksinfo',
            name='btitle',
            field=models.CharField(max_length=50),
        ),
    ]
