# Generated by Django 2.0.2 on 2018-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_books', '0003_auto_20180909_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinfo',
            name='publication_date',
            field=models.CharField(max_length=20),
        ),
    ]
