# Generated by Django 2.0.2 on 2018-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_books', '0004_auto_20180909_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinfo',
            name='bprice',
            field=models.CharField(max_length=50),
        ),
    ]
