# Generated by Django 2.0.2 on 2018-09-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_books', '0006_auto_20180909_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksinfo',
            name='bfile_azw3',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='bfile_epub',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='bfile_mobi',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='bfile_pdf',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='bfile_txt',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='gclick',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='gprice',
        ),
        migrations.RemoveField(
            model_name='booksinfo',
            name='gtype',
        ),
    ]
