# Generated by Django 2.0.2 on 2018-09-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_books', '0007_auto_20180909_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksinfo',
            name='isDelete',
        ),
    ]
