# Generated by Django 2.0.2 on 2018-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gfile',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(upload_to='static/goods'),
        ),
    ]
