# Generated by Django 2.0.2 on 2018-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailinfo',
            name='file',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
    ]
